//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordBarrage.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordBarrage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 abbreviation　n.节略，缩写，缩短  
        ///abide　vt.遵守　vt.忍受  
        ///abolish　vt.废除，取消  
        ///absent　a.不在意的  
        ///absorption　n.吸收；专注  
        ///abstract　a.理论上的　n.抽象  
        ///absurd　a.不合理的，荒唐的  
        ///abundance　n.丰富，充裕  
        ///accessory　n.同谋　a.附属的  
        ///accord　n.调和，符合；协议  
        ///acknowledge　vt.承认；告知收到  
        ///acquaint　vt.使认识，使了解  
        ///action　n.作用；情节  
        ///adhere　vi.粘附；追随；坚持  
        ///adjacent　a.毗连的；紧接着的  
        ///adjoin　vt.贴近，毗连；靠近  
        ///adjustable　a.可调整的，可校准的  
        ///administration　n.局(或署、处等)  
        ///admiration　n.钦佩；赞美，羡慕  
        ///adoption　n.收养；采纳，采取  
        ///adore　vt.崇拜；很喜欢  
        ///advantageous　a.有利的，有助的  
        ///advertise　vt [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
